### ISSUE TITLE
Ensure only one listener is allowed when creating the Hybrid Connection for "auto" mode

### ISSUE THREAD

**Issue by drub0y** [HackedBrain/ikspoz#27]
The current logic for creating the Hybrid Connection for "auto" mode does not specify a limit to the number of listeners. We should specify a limit of one on this connection because there is no benefit to allowing multiple and can only lead to issues with connections accidentally being opened from multiple `ikspoz` clients.

**Comment by luisamiranda** [comment]
https://docs.microsoft.com/en-us/rest/api/relay/hybridconnections/createorupdate#request-body

It is not possible to limit the number of listeners on a connection.
